"""add_rating_column_to_posts

Revision ID: 236a924c6a65
Revises: 26009f341681
Create Date: 2026-05-06 20:05:58.441846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '236a924c6a65'
down_revision: Union[str, Sequence[str], None] = '26009f341681'      # ← Zanjir!
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'rating')
    # ### end Alembic commands ###
